CELL_VOID = 0
CELL_TAVERN = 5
CELL_MINE = 6
CELL_OWN_MINE = 7
CELL_HERO_SPAWN = 8
CELL_WALL = 9

ACTION_NORTH = 'North'
ACTION_SOUTH = 'South'
ACTION_WEST = 'West'
ACTION_EAST = 'East'
ACTION_STAY = 'Stay'
ACTION_SET = (ACTION_NORTH, ACTION_SOUTH, ACTION_WEST, ACTION_EAST, ACTION_STAY)

PROB_FORWARD = 'F'
PROB_BACKWARD = 'B'
PROB_LEFT = 'L'
PROB_RIGHT = 'R'
PROB_STAY = "S"
